/**
 * Copyright (c) 2013 Oculus Info Inc. 
 * http://www.oculusinfo.com/
 * 
 * Released under the MIT License.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Two letter country codes to full names
 */
define(
	function() {
		var countries = [
         {
    	    isoCC2:"AD",
    	    isoCC3:"AND",
    	    name:"Andorra",
    	    latitude:42.5,
    	    longitude:1.6,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AE",
    	    isoCC3:"ARE",
    	    name:"United Arab Emirates",
    	    latitude:24,
    	    longitude:54,
    	    amlRiskScore:6.32,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"AF",
    	    isoCC3:"AFG",
    	    name:"Afghanistan",
    	    latitude:33,
    	    longitude:65,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AG",
    	    isoCC3:"ATG",
    	    name:"Antigua and Barbuda",
    	    latitude:17.05,
    	    longitude:-61.8,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AI",
    	    isoCC3:"AIA",
    	    name:"Anguilla",
    	    latitude:18.25,
    	    longitude:-63.1667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AL",
    	    isoCC3:"ALB",
    	    name:"Albania",
    	    latitude:41,
    	    longitude:20,
    	    amlRiskScore:5.48,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"AM",
    	    isoCC3:"ARM",
    	    name:"Armenia",
    	    latitude:40,
    	    longitude:45,
    	    amlRiskScore:5.13,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"AN",
    	    isoCC3:"ANT",
    	    name:"Netherlands Antilles",
    	    latitude:12.25,
    	    longitude:-68.75,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AO",
    	    isoCC3:"AGO",
    	    name:"Angola",
    	    latitude:-12.5,
    	    longitude:18.5,
    	    amlRiskScore:5.75,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"AQ",
    	    isoCC3:"ATA",
    	    name:"Antarctica",
    	    latitude:-90,
    	    longitude:0,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AR",
    	    isoCC3:"ARG",
    	    name:"Argentina",
    	    latitude:-34,
    	    longitude:-64,
    	    amlRiskScore:7.35,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"AS",
    	    isoCC3:"ASM",
    	    name:"American Samoa",
    	    latitude:-14.3333,
    	    longitude:-170,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AT",
    	    isoCC3:"AUT",
    	    name:"Austria",
    	    latitude:47.3333,
    	    longitude:13.3333,
    	    amlRiskScore:5.74,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"AU",
    	    isoCC3:"AUS",
    	    name:"Australia",
    	    latitude:-27,
    	    longitude:133,
    	    amlRiskScore:4.37,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"AW",
    	    isoCC3:"ABW",
    	    name:"Aruba",
    	    latitude:12.5,
    	    longitude:-69.9667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"AZ",
    	    isoCC3:"AZE",
    	    name:"Azerbaijan",
    	    latitude:40.5,
    	    longitude:47.5,
    	    amlRiskScore:6.49,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BA",
    	    isoCC3:"BIH",
    	    name:"Bosnia and Herzegovina",
    	    latitude:44,
    	    longitude:18,
    	    amlRiskScore:5.71,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BB",
    	    isoCC3:"BRB",
    	    name:"Barbados",
    	    latitude:13.1667,
    	    longitude:-59.5333,
    	    amlRiskScore:5.04,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BD",
    	    isoCC3:"BGD",
    	    name:"Bangladesh",
    	    latitude:24,
    	    longitude:90,
    	    amlRiskScore:6.28,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BE",
    	    isoCC3:"BEL",
    	    name:"Belgium",
    	    latitude:50.8333,
    	    longitude:4,
    	    amlRiskScore:4.22,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"BF",
    	    isoCC3:"BFA",
    	    name:"Burkina Faso",
    	    latitude:13,
    	    longitude:-2,
    	    amlRiskScore:7.39,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"BG",
    	    isoCC3:"BGR",
    	    name:"Bulgaria",
    	    latitude:43,
    	    longitude:25,
    	    amlRiskScore:4.24,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"BH",
    	    isoCC3:"BHR",
    	    name:"Bahrain",
    	    latitude:26,
    	    longitude:50.55,
    	    amlRiskScore:5.71,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BI",
    	    isoCC3:"BDI",
    	    name:"Burundi",
    	    latitude:-3.5,
    	    longitude:30,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"BJ",
    	    isoCC3:"BEN",
    	    name:"Benin",
    	    latitude:9.5,
    	    longitude:2.25,
    	    amlRiskScore:6.81,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"BM",
    	    isoCC3:"BMU",
    	    name:"Bermuda",
    	    latitude:32.3333,
    	    longitude:-64.75,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"BN",
    	    isoCC3:"BRN",
    	    name:"Brunei Darussalam",
    	    latitude:4.5,
    	    longitude:114.6667,
    	    amlRiskScore:5.95,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BO",
    	    isoCC3:"BOL",
    	    name:"Bolivia",
    	    latitude:-17,
    	    longitude:-65,
    	    amlRiskScore:7.25,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"BR",
    	    isoCC3:"BRA",
    	    name:"Brazil",
    	    latitude:-10,
    	    longitude:-55,
    	    amlRiskScore:5.55,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BS",
    	    isoCC3:"BHS",
    	    name:"Bahamas",
    	    latitude:24.25,
    	    longitude:-76,
    	    amlRiskScore:6.37,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BT",
    	    isoCC3:"BTN",
    	    name:"Bhutan",
    	    latitude:27.5,
    	    longitude:90.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"BV",
    	    isoCC3:"BVT",
    	    name:"Bouvet Island",
    	    latitude:-54.4333,
    	    longitude:3.4,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"BW",
    	    isoCC3:"BWA",
    	    name:"Botswana",
    	    latitude:-22,
    	    longitude:24,
    	    amlRiskScore:5.84,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BY",
    	    isoCC3:"BLR",
    	    name:"Belarus",
    	    latitude:53,
    	    longitude:28,
    	    amlRiskScore:5.42,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"BZ",
    	    isoCC3:"BLZ",
    	    name:"Belize",
    	    latitude:17.25,
    	    longitude:-88.75,
    	    amlRiskScore:7.44,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"CA",
    	    isoCC3:"CAN",
    	    name:"Canada",
    	    latitude:60,
    	    longitude:-95,
    	    amlRiskScore:5,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"CC",
    	    isoCC3:"CCK",
    	    name:"Cocos (Keeling) Islands",
    	    latitude:-12.5,
    	    longitude:96.8333,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CD",
    	    isoCC3:"COD",
    	    name:"Congo, the Democratic Republic of the",
    	    latitude:0,
    	    longitude:25,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CF",
    	    isoCC3:"CAF",
    	    name:"Central African Republic",
    	    latitude:7,
    	    longitude:21,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CG",
    	    isoCC3:"COG",
    	    name:"Congo",
    	    latitude:-1,
    	    longitude:15,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CH",
    	    isoCC3:"CHE",
    	    name:"Switzerland",
    	    latitude:47,
    	    longitude:8,
    	    amlRiskScore:5.78,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"CI",
    	    isoCC3:"CIV",
    	    name:"Côte d'Ivoire",
    	    latitude:8,
    	    longitude:-5,
    	    amlRiskScore:5.52,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"CK",
    	    isoCC3:"COK",
    	    name:"Cook Islands",
    	    latitude:-21.2333,
    	    longitude:-159.7667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CL",
    	    isoCC3:"CHL",
    	    name:"Chile",
    	    latitude:-30,
    	    longitude:-71,
    	    amlRiskScore:4.08,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"CM",
    	    isoCC3:"CMR",
    	    name:"Cameroon",
    	    latitude:6,
    	    longitude:12,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CN",
    	    isoCC3:"CHN",
    	    name:"China",
    	    latitude:35,
    	    longitude:105,
    	    amlRiskScore:6.02,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"CO",
    	    isoCC3:"COL",
    	    name:"Colombia",
    	    latitude:4,
    	    longitude:-72,
    	    amlRiskScore:4.64,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"CR",
    	    isoCC3:"CRI",
    	    name:"Costa Rica",
    	    latitude:10,
    	    longitude:-84,
    	    amlRiskScore:6.5,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"CU",
    	    isoCC3:"CUB",
    	    name:"Cuba",
    	    latitude:21.5,
    	    longitude:-80,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CV",
    	    isoCC3:"CPV",
    	    name:"Cape Verde",
    	    latitude:16,
    	    longitude:-24,
    	    amlRiskScore:6.97,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"CX",
    	    isoCC3:"CXR",
    	    name:"Christmas Island",
    	    latitude:-10.5,
    	    longitude:105.6667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"CY",
    	    isoCC3:"CYP",
    	    name:"Cyprus",
    	    latitude:35,
    	    longitude:33,
    	    amlRiskScore:4.93,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"CZ",
    	    isoCC3:"CZE",
    	    name:"Czech Republic",
    	    latitude:49.75,
    	    longitude:15.5,
    	    amlRiskScore:4.81,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"DE",
    	    isoCC3:"DEU",
    	    name:"Germany",
    	    latitude:51,
    	    longitude:9,
    	    amlRiskScore:5.8,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"DJ",
    	    isoCC3:"DJI",
    	    name:"Djibouti",
    	    latitude:11.5,
    	    longitude:43,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"DK",
    	    isoCC3:"DNK",
    	    name:"Denmark",
    	    latitude:56,
    	    longitude:10,
    	    amlRiskScore:4.3,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"DM",
    	    isoCC3:"DMA",
    	    name:"Dominica",
    	    latitude:15.4167,
    	    longitude:-61.3333,
    	    amlRiskScore:5.85,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"DO",
    	    isoCC3:"DOM",
    	    name:"Dominican Republic",
    	    latitude:19,
    	    longitude:-70.6667,
    	    amlRiskScore:7.17,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"DZ",
    	    isoCC3:"DZA",
    	    name:"Algeria",
    	    latitude:28,
    	    longitude:3,
    	    amlRiskScore:5.5,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"EC",
    	    isoCC3:"ECU",
    	    name:"Ecuador",
    	    latitude:-2,
    	    longitude:-77.5,
    	    amlRiskScore:6.89,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"EE",
    	    isoCC3:"EST",
    	    name:"Estonia",
    	    latitude:59,
    	    longitude:26,
    	    amlRiskScore:3.28,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"EG",
    	    isoCC3:"EGY",
    	    name:"Egypt",
    	    latitude:27,
    	    longitude:30,
    	    amlRiskScore:4.98,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"EH",
    	    isoCC3:"ESH",
    	    name:"Western Sahara",
    	    latitude:24.5,
    	    longitude:-13,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"ER",
    	    isoCC3:"ERI",
    	    name:"Eritrea",
    	    latitude:15,
    	    longitude:39,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"ES",
    	    isoCC3:"ESP",
    	    name:"Spain",
    	    latitude:40,
    	    longitude:-4,
    	    amlRiskScore:5.15,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"ET",
    	    isoCC3:"ETH",
    	    name:"Ethiopia",
    	    latitude:8,
    	    longitude:38,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"FI",
    	    isoCC3:"FIN",
    	    name:"Finland",
    	    latitude:64,
    	    longitude:26,
    	    amlRiskScore:3.59,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"FJ",
    	    isoCC3:"FJI",
    	    name:"Fiji",
    	    latitude:-18,
    	    longitude:175,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"FK",
    	    isoCC3:"FLK",
    	    name:"Falkland Islands (Malvinas)",
    	    latitude:-51.75,
    	    longitude:-59,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"FM",
    	    isoCC3:"FSM",
    	    name:"Micronesia, Federated States of",
    	    latitude:6.9167,
    	    longitude:158.25,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"FO",
    	    isoCC3:"FRO",
    	    name:"Faroe Islands",
    	    latitude:62,
    	    longitude:-7,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"FR",
    	    isoCC3:"FRA",
    	    name:"France",
    	    latitude:46,
    	    longitude:2,
    	    amlRiskScore:4.14,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"GA",
    	    isoCC3:"GAB",
    	    name:"Gabon",
    	    latitude:-1,
    	    longitude:11.75,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GB",
    	    isoCC3:"GBR",
    	    name:"United Kingdom",
    	    latitude:54,
    	    longitude:-2,
    	    amlRiskScore:4.66,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"GD",
    	    isoCC3:"GRD",
    	    name:"Grenada",
    	    latitude:12.1167,
    	    longitude:-61.6667,
    	    amlRiskScore:5.47,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"GE",
    	    isoCC3:"GEO",
    	    name:"Georgia",
    	    latitude:42,
    	    longitude:43.5,
    	    amlRiskScore:5.64,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"GF",
    	    isoCC3:"GUF",
    	    name:"French Guiana",
    	    latitude:4,
    	    longitude:-53,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GG",
    	    isoCC3:"GGY",
    	    name:"Guernsey",
    	    latitude:49.5,
    	    longitude:-2.56,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GH",
    	    isoCC3:"GHA",
    	    name:"Ghana",
    	    latitude:8,
    	    longitude:-2,
    	    amlRiskScore:6.04,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"GI",
    	    isoCC3:"GIB",
    	    name:"Gibraltar",
    	    latitude:36.1833,
    	    longitude:-5.3667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GL",
    	    isoCC3:"GRL",
    	    name:"Greenland",
    	    latitude:72,
    	    longitude:-40,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GM",
    	    isoCC3:"GMB",
    	    name:"Gambia",
    	    latitude:13.4667,
    	    longitude:-16.5667,
    	    amlRiskScore:6.48,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"GN",
    	    isoCC3:"GIN",
    	    name:"Guinea",
    	    latitude:11,
    	    longitude:-10,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GP",
    	    isoCC3:"GLP",
    	    name:"Guadeloupe",
    	    latitude:16.25,
    	    longitude:-61.5833,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GQ",
    	    isoCC3:"GNQ",
    	    name:"Equatorial Guinea",
    	    latitude:2,
    	    longitude:10,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GR",
    	    isoCC3:"GRC",
    	    name:"Greece",
    	    latitude:39,
    	    longitude:22,
    	    amlRiskScore:6.78,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"GS",
    	    isoCC3:"SGS",
    	    name:"South Georgia and the South Sandwich Islands",
    	    latitude:-54.5,
    	    longitude:-37,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GT",
    	    isoCC3:"GTM",
    	    name:"Guatemala",
    	    latitude:15.5,
    	    longitude:-90.25,
    	    amlRiskScore:6.01,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"GU",
    	    isoCC3:"GUM",
    	    name:"Guam",
    	    latitude:13.4667,
    	    longitude:144.7833,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GW",
    	    isoCC3:"GNB",
    	    name:"Guinea-Bissau",
    	    latitude:12,
    	    longitude:-15,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"GY",
    	    isoCC3:"GUY",
    	    name:"Guyana",
    	    latitude:5,
    	    longitude:-59,
    	    amlRiskScore:5.17,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"HK",
    	    isoCC3:"HKG",
    	    name:"Hong Kong",
    	    latitude:22.25,
    	    longitude:114.1667,
    	    amlRiskScore:5.51,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"HM",
    	    isoCC3:"HMD",
    	    name:"Heard Island and McDonald Islands",
    	    latitude:-53.1,
    	    longitude:72.5167,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"HN",
    	    isoCC3:"HND",
    	    name:"Honduras",
    	    latitude:15,
    	    longitude:-86.5,
    	    amlRiskScore:6.02,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"HR",
    	    isoCC3:"HRV",
    	    name:"Croatia",
    	    latitude:45.1667,
    	    longitude:15.5,
    	    amlRiskScore:5.8,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"HT",
    	    isoCC3:"HTI",
    	    name:"Haiti",
    	    latitude:19,
    	    longitude:-72.4167,
    	    amlRiskScore:8.16,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"HU",
    	    isoCC3:"HUN",
    	    name:"Hungary",
    	    latitude:47,
    	    longitude:20,
    	    amlRiskScore:4.29,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"ID",
    	    isoCC3:"IDN",
    	    name:"Indonesia",
    	    latitude:-5,
    	    longitude:120,
    	    amlRiskScore:6.38,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"IE",
    	    isoCC3:"IRL",
    	    name:"Ireland",
    	    latitude:53,
    	    longitude:-8,
    	    amlRiskScore:4.52,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"IL",
    	    isoCC3:"ISR",
    	    name:"Israel",
    	    latitude:31.5,
    	    longitude:34.75,
    	    amlRiskScore:4.96,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"IM",
    	    isoCC3:"IMN",
    	    name:"Isle of Man",
    	    latitude:54.23,
    	    longitude:-4.55,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"IN",
    	    isoCC3:"IND",
    	    name:"India",
    	    latitude:20,
    	    longitude:77,
    	    amlRiskScore:6.05,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"IO",
    	    isoCC3:"IOT",
    	    name:"British Indian Ocean Territory",
    	    latitude:-6,
    	    longitude:71.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"IQ",
    	    isoCC3:"IRQ",
    	    name:"Iraq",
    	    latitude:33,
    	    longitude:44,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"IR",
    	    isoCC3:"IRN",
    	    name:"Iran",
    	    latitude:32,
    	    longitude:53,
    	    amlRiskScore:8.57,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"IS",
    	    isoCC3:"ISL",
    	    name:"Iceland",
    	    latitude:65,
    	    longitude:-18,
    	    amlRiskScore:4.18,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"IT",
    	    isoCC3:"ITA",
    	    name:"Italy",
    	    latitude:42.8333,
    	    longitude:12.8333,
    	    amlRiskScore:5.49,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"JE",
    	    isoCC3:"JEY",
    	    name:"Jersey",
    	    latitude:49.21,
    	    longitude:-2.13,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"JM",
    	    isoCC3:"JAM",
    	    name:"Jamaica",
    	    latitude:18.25,
    	    longitude:-77.5,
    	    amlRiskScore:4.77,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"JO",
    	    isoCC3:"JOR",
    	    name:"Jordan",
    	    latitude:31,
    	    longitude:36,
    	    amlRiskScore:5.55,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"JP",
    	    isoCC3:"JPN",
    	    name:"Japan",
    	    latitude:36,
    	    longitude:138,
    	    amlRiskScore:5.88,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"KE",
    	    isoCC3:"KEN",
    	    name:"Kenya",
    	    latitude:1,
    	    longitude:38,
    	    amlRiskScore:8.49,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"KG",
    	    isoCC3:"KGZ",
    	    name:"Kyrgyzstan",
    	    latitude:41,
    	    longitude:75,
    	    amlRiskScore:6.31,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"KH",
    	    isoCC3:"KHM",
    	    name:"Cambodia",
    	    latitude:13,
    	    longitude:105,
    	    amlRiskScore:8.46,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"KI",
    	    isoCC3:"KIR",
    	    name:"Kiribati",
    	    latitude:1.4167,
    	    longitude:173,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"KM",
    	    isoCC3:"COM",
    	    name:"Comoros",
    	    latitude:-12.1667,
    	    longitude:44.25,
    	    amlRiskScore:7.04,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"KN",
    	    isoCC3:"KNA",
    	    name:"Saint Kitts and Nevis",
    	    latitude:17.3333,
    	    longitude:-62.75,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"KP",
    	    isoCC3:"PRK",
    	    name:"North Korea",
    	    latitude:40,
    	    longitude:127,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"KR",
    	    isoCC3:"KOR",
    	    name:"South Korea",
    	    latitude:37,
    	    longitude:127.5,
    	    amlRiskScore:5.5,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"KW",
    	    isoCC3:"KWT",
    	    name:"Kuwait",
    	    latitude:29.3375,
    	    longitude:47.6581,
    	    amlRiskScore:6.1,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"KY",
    	    isoCC3:"CYM",
    	    name:"Cayman Islands",
    	    latitude:19.5,
    	    longitude:-80.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"KZ",
    	    isoCC3:"KAZ",
    	    name:"Kazakhstan",
    	    latitude:48,
    	    longitude:68,
    	    amlRiskScore:5.12,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"LA",
    	    isoCC3:"LAO",
    	    name:"Lao People's Democratic Republic",
    	    latitude:18,
    	    longitude:105,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"LB",
    	    isoCC3:"LBN",
    	    name:"Lebanon",
    	    latitude:33.8333,
    	    longitude:35.8333,
    	    amlRiskScore:6.62,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"LC",
    	    isoCC3:"LCA",
    	    name:"Saint Lucia",
    	    latitude:13.8833,
    	    longitude:-61.1333,
    	    amlRiskScore:6.03,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"LI",
    	    isoCC3:"LIE",
    	    name:"Liechtenstein",
    	    latitude:47.1667,
    	    longitude:9.5333,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"LK",
    	    isoCC3:"LKA",
    	    name:"Sri Lanka",
    	    latitude:7,
    	    longitude:81,
    	    amlRiskScore:6.42,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"LR",
    	    isoCC3:"LBR",
    	    name:"Liberia",
    	    latitude:6.5,
    	    longitude:-9.5,
    	    amlRiskScore:7.35,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"LS",
    	    isoCC3:"LSO",
    	    name:"Lesotho",
    	    latitude:-29.5,
    	    longitude:28.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"LT",
    	    isoCC3:"LTU",
    	    name:"Lithuania",
    	    latitude:56,
    	    longitude:24,
    	    amlRiskScore:3.96,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"LU",
    	    isoCC3:"LUX",
    	    name:"Luxembourg",
    	    latitude:49.75,
    	    longitude:6.1667,
    	    amlRiskScore:6.17,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"LV",
    	    isoCC3:"LVA",
    	    name:"Latvia",
    	    latitude:57,
    	    longitude:25,
    	    amlRiskScore:5.36,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"LY",
    	    isoCC3:"LBY",
    	    name:"Libyan Arab Jamahiriya",
    	    latitude:25,
    	    longitude:17,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MA",
    	    isoCC3:"MAR",
    	    name:"Morocco",
    	    latitude:32,
    	    longitude:-5,
    	    amlRiskScore:5.97,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MC",
    	    isoCC3:"MCO",
    	    name:"Monaco",
    	    latitude:43.7333,
    	    longitude:7.4,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MD",
    	    isoCC3:"MDA",
    	    name:"Moldova",
    	    latitude:47,
    	    longitude:29,
    	    amlRiskScore:5.93,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"ME",
    	    isoCC3:"MNE",
    	    name:"Montenegro",
    	    latitude:42,
    	    longitude:19,
    	    amlRiskScore:4.44,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MG",
    	    isoCC3:"MDG",
    	    name:"Madagascar",
    	    latitude:-20,
    	    longitude:47,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MH",
    	    isoCC3:"MHL",
    	    name:"Marshall Islands",
    	    latitude:9,
    	    longitude:168,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MK",
    	    isoCC3:"MKD",
    	    name:"Macedonia",
    	    latitude:41.8333,
    	    longitude:22,
    	    amlRiskScore:5.74,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"ML",
    	    isoCC3:"MLI",
    	    name:"Mali",
    	    latitude:17,
    	    longitude:-4,
    	    amlRiskScore:7.88,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"MM",
    	    isoCC3:"MMR",
    	    name:"Myanmar",
    	    latitude:22,
    	    longitude:98,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MN",
    	    isoCC3:"MNG",
    	    name:"Mongolia",
    	    latitude:46,
    	    longitude:105,
    	    amlRiskScore:6.35,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MO",
    	    isoCC3:"MAC",
    	    name:"Macao",
    	    latitude:22.1667,
    	    longitude:113.55,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MP",
    	    isoCC3:"MNP",
    	    name:"Northern Mariana Islands",
    	    latitude:15.2,
    	    longitude:145.75,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MQ",
    	    isoCC3:"MTQ",
    	    name:"Martinique",
    	    latitude:14.6667,
    	    longitude:-61,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MR",
    	    isoCC3:"MRT",
    	    name:"Mauritania",
    	    latitude:20,
    	    longitude:-12,
    	    amlRiskScore:6.82,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"MS",
    	    isoCC3:"MSR",
    	    name:"Montserrat",
    	    latitude:16.75,
    	    longitude:-62.2,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MT",
    	    isoCC3:"MLT",
    	    name:"Malta",
    	    latitude:35.8333,
    	    longitude:14.5833,
    	    amlRiskScore:4.22,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"MU",
    	    isoCC3:"MUS",
    	    name:"Mauritius",
    	    latitude:-20.2833,
    	    longitude:57.55,
    	    amlRiskScore:5.46,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MV",
    	    isoCC3:"MDV",
    	    name:"Maldives",
    	    latitude:3.25,
    	    longitude:73,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"MW",
    	    isoCC3:"MWI",
    	    name:"Malawi",
    	    latitude:-13.5,
    	    longitude:34,
    	    amlRiskScore:5.72,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MX",
    	    isoCC3:"MEX",
    	    name:"Mexico",
    	    latitude:23,
    	    longitude:-102,
    	    amlRiskScore:5.76,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MY",
    	    isoCC3:"MYS",
    	    name:"Malaysia",
    	    latitude:2.5,
    	    longitude:112.5,
    	    amlRiskScore:5.16,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"MZ",
    	    isoCC3:"MOZ",
    	    name:"Mozambique",
    	    latitude:-18.25,
    	    longitude:35,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"NA",
    	    isoCC3:"NAM",
    	    name:"Namibia",
    	    latitude:-22,
    	    longitude:17,
    	    amlRiskScore:6.8,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"NC",
    	    isoCC3:"NCL",
    	    name:"New Caledonia",
    	    latitude:-21.5,
    	    longitude:165.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"NE",
    	    isoCC3:"NER",
    	    name:"Niger",
    	    latitude:16,
    	    longitude:8,
    	    amlRiskScore:7.11,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"NF",
    	    isoCC3:"NFK",
    	    name:"Norfolk Island",
    	    latitude:-29.0333,
    	    longitude:167.95,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"NG",
    	    isoCC3:"NGA",
    	    name:"Nigeria",
    	    latitude:10,
    	    longitude:8,
    	    amlRiskScore:7.18,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"NI",
    	    isoCC3:"NIC",
    	    name:"Nicaragua",
    	    latitude:13,
    	    longitude:-85,
    	    amlRiskScore:5.87,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"NL",
    	    isoCC3:"NLD",
    	    name:"Netherlands",
    	    latitude:52.5,
    	    longitude:5.75,
    	    amlRiskScore:5.03,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"NO",
    	    isoCC3:"NOR",
    	    name:"Norway",
    	    latitude:62,
    	    longitude:10,
    	    amlRiskScore:2.36,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"NP",
    	    isoCC3:"NPL",
    	    name:"Nepal",
    	    latitude:28,
    	    longitude:84,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"NR",
    	    isoCC3:"NRU",
    	    name:"Nauru",
    	    latitude:-0.5333,
    	    longitude:166.9167,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"NU",
    	    isoCC3:"NIU",
    	    name:"Niue",
    	    latitude:-19.0333,
    	    longitude:-169.8667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"NZ",
    	    isoCC3:"NZL",
    	    name:"New Zealand",
    	    latitude:-41,
    	    longitude:174,
    	    amlRiskScore:3.82,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"OM",
    	    isoCC3:"OMN",
    	    name:"Oman",
    	    latitude:21,
    	    longitude:57,
    	    amlRiskScore:4.6,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"PA",
    	    isoCC3:"PAN",
    	    name:"Panama",
    	    latitude:9,
    	    longitude:-80,
    	    amlRiskScore:5.98,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"PE",
    	    isoCC3:"PER",
    	    name:"Peru",
    	    latitude:-10,
    	    longitude:-76,
    	    amlRiskScore:4.59,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"PF",
    	    isoCC3:"PYF",
    	    name:"French Polynesia",
    	    latitude:-15,
    	    longitude:-140,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PG",
    	    isoCC3:"PNG",
    	    name:"Papua New Guinea",
    	    latitude:-6,
    	    longitude:147,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PH",
    	    isoCC3:"PHL",
    	    name:"Philippines",
    	    latitude:13,
    	    longitude:122,
    	    amlRiskScore:6.64,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"PK",
    	    isoCC3:"PAK",
    	    name:"Pakistan",
    	    latitude:30,
    	    longitude:70,
    	    amlRiskScore:6.75,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"PL",
    	    isoCC3:"POL",
    	    name:"Poland",
    	    latitude:52,
    	    longitude:20,
    	    amlRiskScore:4.74,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"PM",
    	    isoCC3:"SPM",
    	    name:"Saint Pierre and Miquelon",
    	    latitude:46.8333,
    	    longitude:-56.3333,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PN",
    	    isoCC3:"PCN",
    	    name:"Pitcairn",
    	    latitude:-24.7,
    	    longitude:-127.4,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PR",
    	    isoCC3:"PRI",
    	    name:"Puerto Rico",
    	    latitude:18.25,
    	    longitude:-66.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PS",
    	    isoCC3:"PSE",
    	    name:"Palestinian Territory, Occupied",
    	    latitude:32,
    	    longitude:35.25,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PT",
    	    isoCC3:"PRT",
    	    name:"Portugal",
    	    latitude:39.5,
    	    longitude:-8,
    	    amlRiskScore:4.28,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"PW",
    	    isoCC3:"PLW",
    	    name:"Palau",
    	    latitude:7.5,
    	    longitude:134.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"PY",
    	    isoCC3:"PRY",
    	    name:"Paraguay",
    	    latitude:-23,
    	    longitude:-58,
    	    amlRiskScore:7.57,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"QA",
    	    isoCC3:"QAT",
    	    name:"Qatar",
    	    latitude:25.5,
    	    longitude:51.25,
    	    amlRiskScore:5.24,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"RE",
    	    isoCC3:"REU",
    	    name:"Réunion",
    	    latitude:-21.1,
    	    longitude:55.6,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"RO",
    	    isoCC3:"ROU",
    	    name:"Romania",
    	    latitude:46,
    	    longitude:25,
    	    amlRiskScore:4.68,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"RS",
    	    isoCC3:"SRB",
    	    name:"Serbia",
    	    latitude:44,
    	    longitude:21,
    	    amlRiskScore:5.2,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"RU",
    	    isoCC3:"RUS",
    	    name:"Russian Federation",
    	    latitude:60,
    	    longitude:100,
    	    amlRiskScore:5.66,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"RW",
    	    isoCC3:"RWA",
    	    name:"Rwanda",
    	    latitude:-2,
    	    longitude:30,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SA",
    	    isoCC3:"SAU",
    	    name:"Saudi Arabia",
    	    latitude:25,
    	    longitude:45,
    	    amlRiskScore:4.78,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SB",
    	    isoCC3:"SLB",
    	    name:"Solomon Islands",
    	    latitude:-8,
    	    longitude:159,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SC",
    	    isoCC3:"SYC",
    	    name:"Seychelles",
    	    latitude:-4.5833,
    	    longitude:55.6667,
    	    amlRiskScore:6.23,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SD",
    	    isoCC3:"SDN",
    	    name:"Sudan",
    	    latitude:15,
    	    longitude:30,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SE",
    	    isoCC3:"SWE",
    	    name:"Sweden",
    	    latitude:62,
    	    longitude:15,
    	    amlRiskScore:3.5,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"SG",
    	    isoCC3:"SGP",
    	    name:"Singapore",
    	    latitude:1.3667,
    	    longitude:103.8,
    	    amlRiskScore:4.82,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SH",
    	    isoCC3:"SHN",
    	    name:"Saint Helena, Ascension and Tristan da Cunha",
    	    latitude:-15.9333,
    	    longitude:-5.7,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SI",
    	    isoCC3:"SVN",
    	    name:"Slovenia",
    	    latitude:46,
    	    longitude:15,
    	    amlRiskScore:3.37,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"SJ",
    	    isoCC3:"SJM",
    	    name:"Svalbard and Jan Mayen",
    	    latitude:78,
    	    longitude:20,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SK",
    	    isoCC3:"SVK",
    	    name:"Slovakia",
    	    latitude:48.6667,
    	    longitude:19.5,
    	    amlRiskScore:5.47,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SL",
    	    isoCC3:"SLE",
    	    name:"Sierra Leone",
    	    latitude:8.5,
    	    longitude:-11.5,
    	    amlRiskScore:6.97,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"SM",
    	    isoCC3:"SMR",
    	    name:"San Marino",
    	    latitude:43.7667,
    	    longitude:12.4167,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SN",
    	    isoCC3:"SEN",
    	    name:"Senegal",
    	    latitude:14,
    	    longitude:-14,
    	    amlRiskScore:5.55,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SO",
    	    isoCC3:"SOM",
    	    name:"Somalia",
    	    latitude:10,
    	    longitude:49,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SR",
    	    isoCC3:"SUR",
    	    name:"Suriname",
    	    latitude:4,
    	    longitude:-56,
    	    amlRiskScore:6.62,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"ST",
    	    isoCC3:"STP",
    	    name:"Sao Tome and Principe",
    	    latitude:1,
    	    longitude:7,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"SV",
    	    isoCC3:"SLV",
    	    name:"El Salvador",
    	    latitude:13.8333,
    	    longitude:-88.9167,
    	    amlRiskScore:5.08,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SY",
    	    isoCC3:"SYR",
    	    name:"Syrian Arab Republic",
    	    latitude:35,
    	    longitude:38,
    	    amlRiskScore:6.11,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"SZ",
    	    isoCC3:"SWZ",
    	    name:"Swaziland",
    	    latitude:-26.5,
    	    longitude:31.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TC",
    	    isoCC3:"TCA",
    	    name:"Turks and Caicos Islands",
    	    latitude:21.75,
    	    longitude:-71.5833,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TD",
    	    isoCC3:"TCD",
    	    name:"Chad",
    	    latitude:15,
    	    longitude:19,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TF",
    	    isoCC3:"ATF",
    	    name:"French Southern Territories",
    	    latitude:-43,
    	    longitude:67,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TG",
    	    isoCC3:"TGO",
    	    name:"Togo",
    	    latitude:8,
    	    longitude:1.1667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TH",
    	    isoCC3:"THA",
    	    name:"Thailand",
    	    latitude:15,
    	    longitude:100,
    	    amlRiskScore:6.46,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"TJ",
    	    isoCC3:"TJK",
    	    name:"Tajikistan",
    	    latitude:39,
    	    longitude:71,
    	    amlRiskScore:8.12,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"TK",
    	    isoCC3:"TKL",
    	    name:"Tokelau",
    	    latitude:-9,
    	    longitude:-172,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TL",
    	    isoCC3:"TLS",
    	    name:"Timor-Leste",
    	    latitude:-8.55,
    	    longitude:125.5167,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TM",
    	    isoCC3:"TKM",
    	    name:"Turkmenistan",
    	    latitude:40,
    	    longitude:60,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TN",
    	    isoCC3:"TUN",
    	    name:"Tunisia",
    	    latitude:34,
    	    longitude:9,
    	    amlRiskScore:4.96,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"TO",
    	    isoCC3:"TON",
    	    name:"Tonga",
    	    latitude:-20,
    	    longitude:-175,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TR",
    	    isoCC3:"TUR",
    	    name:"Turkey",
    	    latitude:39,
    	    longitude:35,
    	    amlRiskScore:5.99,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"TT",
    	    isoCC3:"TTO",
    	    name:"Trinidad and Tobago",
    	    latitude:11,
    	    longitude:-61,
    	    amlRiskScore:6.67,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"TV",
    	    isoCC3:"TUV",
    	    name:"Tuvalu",
    	    latitude:-8,
    	    longitude:178,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"TW",
    	    isoCC3:"TWN",
    	    name:"Taiwan, Province of China",
    	    latitude:23.5,
    	    longitude:121,
    	    amlRiskScore:5.16,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"TZ",
    	    isoCC3:"TZA",
    	    name:"Tanzania, United Republic of",
    	    latitude:-6,
    	    longitude:35,
    	    amlRiskScore:7.11,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"UA",
    	    isoCC3:"UKR",
    	    name:"Ukraine",
    	    latitude:49,
    	    longitude:32,
    	    amlRiskScore:6.62,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"UG",
    	    isoCC3:"UGA",
    	    name:"Uganda",
    	    latitude:1,
    	    longitude:32,
    	    amlRiskScore:7.63,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"UM",
    	    isoCC3:"UMI",
    	    name:"United States Minor Outlying Islands",
    	    latitude:19.2833,
    	    longitude:166.6,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"US",
    	    isoCC3:"USA",
    	    name:"United States",
    	    latitude:38,
    	    longitude:-97,
    	    amlRiskScore:5.26,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"UY",
    	    isoCC3:"URY",
    	    name:"Uruguay",
    	    latitude:-33,
    	    longitude:-56,
    	    amlRiskScore:5.18,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"UZ",
    	    isoCC3:"UZB",
    	    name:"Uzbekistan",
    	    latitude:41,
    	    longitude:64,
    	    amlRiskScore:5.42,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"VA",
    	    isoCC3:"VAT",
    	    name:"Holy See (Vatican City State)",
    	    latitude:41.9,
    	    longitude:12.45,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"VC",
    	    isoCC3:"VCT",
    	    name:"Saint Vincent and the Grenadines",
    	    latitude:13.25,
    	    longitude:-61.2,
    	    amlRiskScore:5.59,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"VE",
    	    isoCC3:"VEN",
    	    name:"Venezuela, Bolivarian Republic of",
    	    latitude:8,
    	    longitude:-66,
    	    amlRiskScore:6.62,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"VG",
    	    isoCC3:"VGB",
    	    name:"Virgin Islands, British",
    	    latitude:18.5,
    	    longitude:-64.5,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"VI",
    	    isoCC3:"VIR",
    	    name:"Virgin Islands, U.S.",
    	    latitude:18.3333,
    	    longitude:-64.8333,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"VN",
    	    isoCC3:"VNM",
    	    name:"Viet Nam",
    	    latitude:16,
    	    longitude:106,
    	    amlRiskScore:6.83,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"VU",
    	    isoCC3:"VUT",
    	    name:"Vanuatu",
    	    latitude:-16,
    	    longitude:167,
    	    amlRiskScore:5.79,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"WF",
    	    isoCC3:"WLF",
    	    name:"Wallis and Futuna",
    	    latitude:-13.3,
    	    longitude:-176.2,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"WS",
    	    isoCC3:"WSM",
    	    name:"Samoa",
    	    latitude:-13.5833,
    	    longitude:-172.3333,
    	    amlRiskScore:5.97,
    	    amlRiskClassification:"M"
    	  },
    	  {
    	    isoCC2:"XK",
    	    isoCC3:"XKX",
    	    name:"Kosovo",
    	    latitude:42.6,
    	    longitude:20.85,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"YE",
    	    isoCC3:"YEM",
    	    name:"Yemen",
    	    latitude:15,
    	    longitude:48,
    	    amlRiskScore:7.32,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"YT",
    	    isoCC3:"MYT",
    	    name:"Mayotte",
    	    latitude:-12.8333,
    	    longitude:45.1667,
    	    amlRiskScore:null,
    	    amlRiskClassification:""
    	  },
    	  {
    	    isoCC2:"ZA",
    	    isoCC3:"ZAF",
    	    name:"South Africa",
    	    latitude:-29,
    	    longitude:24,
    	    amlRiskScore:4.12,
    	    amlRiskClassification:"L"
    	  },
    	  {
    	    isoCC2:"ZM",
    	    isoCC3:"ZMB",
    	    name:"Zambia",
    	    latitude:-15,
    	    longitude:30,
    	    amlRiskScore:7.41,
    	    amlRiskClassification:"H"
    	  },
    	  {
    	    isoCC2:"ZW",
    	    isoCC3:"ZWE",
    	    name:"Zimbabwe",
    	    latitude:-20,
    	    longitude:30,
    	    amlRiskScore:7.11,
    	    amlRiskClassification:"H"
    	  }
    	];
		
		var i, len = countries.length, country, cc2= {}, cc3= {};
		
		for (i=0; i< len; i++) {
			country = countries[i];
			
			cc2[country.isoCC2] = country;
			cc3[country.isoCC3] = country;
		}
		
		return {
			name : function( code ) {
				if (code && code.trim) {
					code = code.trim();
					
					var c = null;
					
					switch (code.length) {
					case 2:
						c = cc2[code];
						break;
					case 3:
						c = cc3[code];
						break;
					}
					return c && c.name;
				}
			},
			isoCC3 : function( code ) {
				if (code && code.trim) {
					code = code.trim();
					
					var c = null;
					
					switch (code.length) {
					case 2:
						c = cc2[code];
						break;
					case 3:
						c = cc3[code];
						break;
					}
					return c && c.isoCC3;
				}
			}
		};
	}()
);
